package customers.ui;

import customers.controller.CustomerController;
import customers.domain.Customer;

public class CreateCustomer extends javax.swing.JFrame {
    
    //esta lista de clientes ahora est en mi customerController
    //private List<Customer> customerList = new ArrayList<>();
    private CustomerController customerController = new CustomerController();

    // Creates new form CreateCustomer
    public CreateCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        textFieldFirstName = new javax.swing.JTextField();
        textFieldNationalId = new javax.swing.JTextField();
        textFieldlastName = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelDni = new javax.swing.JLabel();
        ButtonGuardar = new javax.swing.JButton();
        ButtonGetCustomers = new javax.swing.JButton();
        labelCustomerList = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setText("Ingrese los datos del cliente y luego pulse Guardar");
        getContentPane().add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));
        getContentPane().add(textFieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 200, -1));

        textFieldNationalId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNationalIdActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldNationalId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 200, -1));

        textFieldlastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldlastNameActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldlastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 200, -1));

        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 50, 60, -1));

        jLabelApellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelApellido.setText("Apellido:");
        getContentPane().add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 90, 60, -1));

        jLabelDni.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDni.setText("Doc. Nacional:");
        getContentPane().add(jLabelDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, 20));

        ButtonGuardar.setText("Guardar");
        ButtonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonGuardarMouseClicked(evt);
            }
        });
        ButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        ButtonGetCustomers.setText("Mostrar Clientes");
        ButtonGetCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonGetCustomersMouseClicked(evt);
            }
        });
        getContentPane().add(ButtonGetCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        labelCustomerList.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelCustomerList.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(labelCustomerList, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 250, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNationalIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNationalIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNationalIdActionPerformed

    private void textFieldlastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldlastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldlastNameActionPerformed

    private void ButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonGuardarActionPerformed

    private void ButtonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonGuardarMouseClicked
        /* Ahora lo paso a mi customerController
        Customer customer = new Customer(); 
        customer.setFirstname(textFieldFirstName.getText());
        customer.setLastname(textFieldlastName.getText());
        customer.setNationalId(textFieldNationalId.getText());
        
        //para imprimir el objeto asi veo que se setteo
        //System.out.println(customer);
        //agrego el customer a mi ArrayList
        customerList.add(customer);
        */
               
        customerController.createCustomer(
                textFieldFirstName.getText(), 
                textFieldlastName.getText(), 
                textFieldNationalId.getText());
        
        //Y voy a setear los campos nombre, apellido dni a vacio para que queden limpios 
        //para el proximo cliente
        textFieldFirstName.setText("");
        textFieldlastName.setText("");
        textFieldNationalId.setText("");
    }//GEN-LAST:event_ButtonGuardarMouseClicked

    private void ButtonGetCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonGetCustomersMouseClicked
        //instancio una variable Sring vacia
        String customerListString ="";
        //recorro el Arraylist de clientes elemento por elemento
        /* dejo comentado porque utilizo el for each - for mejorado
        for (int i = 0;  i < customerList.size(); i++) {
            //agarro el First Name y los voy concatenando
            customerListString = customerListString.concat(customerList.get(i).toString());
            customerListString = customerListString.concat("<br>");
        }
        */
          for ( Customer c : customerController.getAllCustomers() ) {
            customerListString = customerListString.concat(c.toString());
            customerListString = customerListString.concat("<br>");
        }
        labelCustomerList.setText("<html>"+customerListString+"</html>");
    }//GEN-LAST:event_ButtonGetCustomersMouseClicked


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonGetCustomers;
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel labelCustomerList;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTextField textFieldFirstName;
    private javax.swing.JTextField textFieldNationalId;
    private javax.swing.JTextField textFieldlastName;
    // End of variables declaration//GEN-END:variables
}
